---
- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - ttf-impallari-cabin-font # cv font
      - glow # render markdown cli
      - zrepl # zfs snapshot manager

- name: install base packages
  pacman:
    name:
      # Main
      - ttf-jetbrains-mono # main font
      - noto-fonts         # unicode font
      # Shell
      - fish               # powerful shell
      - starship           # cross-shell prompt
      - git                #
      - exa                # powerful ls
      - bc                 # maths
      - jq                 # json processor
      - most               # colorized pager
      - bat                # colorized cat
      - neovim             # futur of vim
      - tree               #
      - vi                 #
      - man                #
      - screen             # terminal multiplexer
      - asciinema          # term recorder
      - expect             # automation tool
      - arch-audit         # list vulnerabilities
      # System
      - htop               # system monitor
      - net-tools          # netstat
      - reflector          # mirror sorter
      - fwupd              # dell firmware updater
      - nmap               # port scanner
      - tcpdump            # packet analyzer
      - whois              # query registry
      - stress             # stress test tool
      # Disk
      - iotop              # disk "top"
      - ncdu               # disk usage analyzer
      # Network
      - nethogs            # net "top"
      - openssh            #
      - sshpass            # allow ansible -k
      - keychain           # ssh-agent wrapper
      - wget               # downloader
      - bind-tools         # dns tools
      - openbsd-netcat     # network utility
      - speedtest-cli      # 
      # Utils
      - cronie             # Scheduler
      - at                 # Scheduler
      - borgbackup         # backup utility
      - borgmatic          # backup utility automation
      - lsd                # improved ls command
      - rsync              # sync tool
      - rclone             # sync tool
      - syncthing          # sync tool
      - vdirsyncer         # sync tool
      - khal               # cli calendar manager
      - khard              # cli contacts manager
      - words              # dictionnaries
      - fzf                # fuzzy finder
      - neofetch           #
      - unzip              # uncompress zip
      - cifs-utils         #
      - shellcheck         # sh linter
      - oath-toolkit       # otp tool
      - python-pip         # python3 package manager
      - dmidecode          # dump dmi table content
      - python-pre-commit  # pre-commit hook manager
      - zim                # wiki app
    state: present

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'

- name: set timezone
  shell: timedatectl set-timezone Europe/Paris

- name: set ntp
  shell: timedatectl set-ntp true
