---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - brightnessctl # brightness manager
      - wofi # rofi for wayland
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-intel
      - lib32-vulkan-intel
      - intel-media-driver
      - libva-utils
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - evince # pdf viewer
      - evolution # mail client
      - gnome-keyring # evolution gnome keyring
      - seahorse # keyring manager
      - firefox
      - firefox-i18n-fr
      - flatpak # package manager
      - gimp # img editor
      - kolourpaint # img editor
      - shotwell # photo manager
      - libreoffice-still-fr # libreoffice suite fr
      - lollypop # music player
      - lxappearance # theme manager
      - mpv # video player
      - thunar # file manager
      - tumbler # thumbnailer
      - openvpn
      - playerctl # music player cli controller
      - rdesktop # remote desktop client
      - steam # games manager
      - transmission-gtk # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - texlive-fontsextra # latex
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - gnome-themes-extra # gtk themes
      - x2goclient 
      - youtube-dl
      - gopass # password manager
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv --keyserver keyserver.ubuntu.com '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
      - equilux-theme 
      - wdisplays-git # arandr for wayland
      - wf-recorder-git # screen recorder for wayland
      - grimshot-git # grim+slurp wrapper
      - swaylock-fancy-git # locker for wayland
      - wob # bars for wayland
      - connman-gtk # connman gtk gui
      #- gnome-ssh-askpass2 # ssh askpass gui
      - google-chrome
      - adb-sync-git # android dir sync
      - downgrade # package downgrader
      - lf # cli file manager
      - molotov # french tv wrapper
      - otf-font-awesome
      #- ttf-impallari-cabin-font # xelatex cv
      - pastel # color viewer
      - tiny-irc-client-git
      - starleaf-breeze
      - swappy # screenshot editor
      - senpai # irc client for soju
